image: develop-registry.4pd.io/centos6_gcc7_fesql:master

before_script:
    - source /opt/rh/python27/enable
    - export JAVA_HOME=/depends/thirdparty/jdk1.8.0_141/
    - export PATH=$PATH:/depends/thirdparty/apache-maven-3.6.3/bin/:/depends/thirdparty/jdk1.8.0_141/bin/:/depends/thirdparty/bin/:/opt/rh/devtoolset-7/root/usr/bin/

stages:
    - build

build_spark:
    stage: build
    script:
        - mvn clean package -DskipTests -Dscalatest.skip=true -Dwagon.skip=true -Dmaven.test.skip=true

upload_spark_distribution:
    stage: build
    except:
        variables:
            - $ENV_BUILD == "daily"
    script:
        -  sed -i 's/$SPARK_HOME\/build\/mvn/mvn/g' ./dev/make-distribution.sh
        - ./dev/make-distribution.sh --name llvm-spark --pip --tgz -Phadoop-2.7 -Pyarn
        - ./upload_spark_distribution.sh
